### ISSUE TITLE
Microcontroller reset does not exit sleep

### ISSUE THREAD

**Issue by klightspeed** [lcgamboa/picsim#1]
Power-on reset and MCLR reset do not clear the pic->sleep flag, and as a result the CPU does not resume from sleep when the reset button is pressed or the power is removed and re-applied in picsimlab while in a sleep state.

**Comment by lcgamboa** [comment]
Fixed in commit  https://github.com/lcgamboa/picsim/commit/2dd44dbb270fb4eb171d8d23e33b0ebb6c06760f .
